version: '3.4'

services:
  pre-print-service:
    image: 127.0.0.1:5001/pre-print-service
    build:
      context: preprintservice_src/
      args:
      # search an appropriate version for your cpu architecture in https://github.com/prusa3d/PrusaSlicer/releases
      # you might also need to install libGLU via 'sudo apt-get install libglu1'
        # - SLIC3R_VERSION=https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.5.1/PrusaSlicer-2.5.1+linux-x64-GTK2-202303151358.tar.bz2
        - SLIC3R_VERSION=https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.5.1/PrusaSlicer-2.5.1+linux-armv7l-GTK2-202303151108.tar.bz2
    ports: 
      - 2304:2304
    restart: always
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
